/*
 * pop_sprites.h - ESP32 port: read pre-decoded Prince of Persia sprite chtabs
 * straight from the flash-embedded blob (assets/pop_sprites.bin, generated by
 * tools/pop_bake_sprites.c). No engine types here so it stays free of the
 * word/byte/far macro soup.
 */
#pragma once

#include <stdint.h>
#include <stddef.h>

/* Parse the embedded blob header. Safe to call once at startup. */
void pop_sprites_init(void);

/* Find a baked chtab by its images DAT file name and base resource id.
 * Returns a chtab index >= 0, or -1 if that (dat, resource) was not baked. */
int pop_sprites_find(const char *dat_name, int resource);

/* Number of image slots in a baked chtab. */
int pop_sprites_n_images(int chtab_idx);

/* Return a flash pointer to the baked 8bpp pixels of image img_i (0-based) and
 * its width/height. Returns NULL (and w=h=0) for an empty/absent image slot.
 * Pixel bytes are palette-row-baked: 0 = transparent, else = row*16 + index. */
const uint8_t *pop_sprites_image(int chtab_idx, int img_i, int *w, int *h);
