/*
 * dat_registry.h - ESP32 port: table of DAT files embedded into the firmware.
 *
 * The table itself (dat_registry.c) is generated by main/CMakeLists.txt from
 * the same file glob used for EMBED_FILES, so it always matches the set of
 * embedded resources. Part of the ESP32 port glue; distributed under GPLv2
 * together with the rest of the project.
 */
#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/** One embedded DAT file: its name plus the linker symbols bounding its bytes. */
typedef struct {
    const char    *name;   /*!< File name, e.g. "TITLE.DAT" */
    const uint8_t *start;  /*!< First byte of the embedded blob */
    const uint8_t *end;    /*!< One past the last byte of the embedded blob */
} embedded_dat_t;

/** Table of every embedded DAT file (generated). */
extern const embedded_dat_t g_embedded_dats[];

/** Number of entries in ::g_embedded_dats (generated). */
extern const size_t g_embedded_dats_count;

#ifdef __cplusplus
}
#endif
